language: bash

services:
    - docker

before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
    - docker build -t wangjw219/myblog:latest .
    - docker push wangjw219/myblog:latest